<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-ios27.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Include="Bios\Fonts\font1.raw" />
      <EmbeddedResource Include="Bios\Fonts\font2.raw" />
      <EmbeddedResource Include="Catalog\data\*.json" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
      <PackageReference Include="MonoMod.RuntimeDetour" Version="25.3.6" />
      <PackageReference Include="NativeFileDialogSharp" Version="0.5.0" />
        <PackageReference Include="Silk.NET.Core" Version="2.23.0" />
        <PackageReference Include="Silk.NET.OpenGL" Version="2.22.0" />
        <PackageReference Include="Silk.NET.OpenAL" Version="2.22.0" />
        <PackageReference Include="Silk.NET.Input" Version="2.22.0" />
        <PackageReference Include="Silk.NET.Maths" Version="2.23.0" />
        <PackageReference Include="Silk.NET.Windowing" Version="2.22.0" />
      <PackageReference Include="Silk.NET.OpenAL.Soft.Native" Version="1.23.1" />
      <PackageReference Include="Silk.NET.OpenGL.Extensions.ImGui" Version="2.22.0" />
      <PackageReference Include="Silk.NET.SDL" Version="2.23.0" />
      <PackageReference Include="StbImageSharp" Version="2.30.15" />
      <PackageReference Include="StbImageWriteSharp" Version="1.16.7" />
    </ItemGroup>

</Project>
